name: Vlaams Parlement Scraper

on:
  schedule:
    # Run on Mondays and Fridays at 5:00 AM UTC
    - cron: '0 5 * * 1,5'
  workflow_dispatch:
    # Allow manual triggering

jobs:
  scrape-parliament-data:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Install numpy first to ensure compatibility
          pip install numpy==1.23.5
          # Then install other dependencies
          if [ -f requirements.txt ]; then pip install -r requirements.txt; else pip install pandas==1.5.3 beautifulsoup4 requests; fi
      
      - name: Run scraper
        run: |
          # Create data directory if it doesn't exist
          mkdir -p data
          python src/main.py
      
      - name: Commit and push changes
        run: |
          # Configure Git
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          
          # Pull the latest changes from the repository
          git pull origin "${GITHUB_REF#refs/heads/}" --rebase
          
          # Add data directory to Git
          git add data/
          
          # Check if there are changes to commit
          if git diff --staged --quiet; then
            echo "No changes to commit"
            exit 0
          fi
          
          # Commit changes
          git commit -m "Update parliament data: $(date +'%Y-%m-%d')"
          
          # Push changes directly using the built-in token
          git push "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" HEAD:"${GITHUB_REF#refs/heads/}"