name: Vlaams Parlement Scraper

on:
  schedule:
    - cron: '0 5 * * 1,5'  # Runs on Mondays and Fridays at 5:00 AM UTC
  workflow_dispatch:

jobs:
  scrape-parliament-data:
    runs-on: ubuntu-latest
    steps:
      - name: Check out main repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install numpy==1.23.5
          if [ -f requirements.txt ]; then 
            pip install -r requirements.txt
          else 
            pip install pandas==1.5.3 beautifulsoup4 requests
          fi

      - name: Run scraper
        run: |
          mkdir -p data
          python src/main.py

      - name: Check out data repository
        uses: actions/checkout@v3
        with:
          repository: gehuybre/commissie_scraper-_saves
          token: ${{ secrets.SCRAPE_SAVE_TOKEN }}
          path: data_repo

      - name: Copy scraped data to data repository
        run: |
          cp -R data/* data_repo/

      - name: Commit and push changes to data repository
        working-directory: data_repo
        run: |
          # Configure Git
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          # Get a fresh snapshot of the remote branch
          git fetch origin "${GITHUB_REF#refs/heads/}"
          git reset --hard origin/"${GITHUB_REF#refs/heads/}"
          
          # Add the data directory to Git
          git add data/
          
          # Commit and push changes if any changes are detected
          if ! git diff --cached --quiet; then
            git commit -m "Update parliament data: $(date +'%Y-%m-%d')"
            git push "https://github.com/gehuybre/commissie_scraper-_saves.git" HEAD:"${GITHUB_REF#refs/heads/}"
          else
            echo "No changes to commit"
          fi
