name: Vlaams Parlement Scraper

on:
  schedule:
    # Run on Mondays and Fridays at 5:00 AM UTC
    - cron: '0 5 * * 1,5'
  workflow_dispatch:
    # Allow manual triggering

jobs:
  scrape-parliament-data:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Install numpy first to ensure compatibility
          pip install numpy==1.23.5
          # Then install other dependencies
          if [ -f requirements.txt ]; then 
            pip install -r requirements.txt
          else 
            pip install pandas==1.5.3 beautifulsoup4 requests
          fi
      
      - name: Run scraper (Test Mode)
        run: |
          # Create data directory if it doesn't exist
          mkdir -p data/test
          # Simulate downloading 3 files
          echo "Test file 1 content" > data/test/file1.txt
          echo "Test file 2 content" > data/test/file2.txt
          echo "Test file 3 content" > data/test/file3.txt
          echo "Simulated scraping complete. 3 files downloaded."
      
      - name: Commit and push changes
        run: |
          # Configure Git
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          # Get a fresh snapshot of the remote branch
          git fetch origin "${GITHUB_REF#refs/heads/}"
          git reset --hard origin/"${GITHUB_REF#refs/heads/}"
          
          # Add the data directory to Git
          git add data/
          
          # Count the number of files staged for commit
          FILE_COUNT=$(git diff --cached --name-only | wc -l)
          echo "Number of files staged for commit: $FILE_COUNT"
          
          # For testing: if exactly 3 files are staged, commit and push; otherwise, exit.
          if [ "$FILE_COUNT" -eq 3 ]; then
            echo "Test condition met: 3 files downloaded. Committing changes."
            git commit -m "Test commit: 3 files downloaded on $(date +'%Y-%m-%d')"
            git push "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" HEAD:"${GITHUB_REF#refs/heads/}"
          else
            echo "Test condition not met (expected 3 files). Exiting without push."
            exit 1
          fi
